### ISSUE TITLE
Extension displayed twice

### ISSUE THREAD

**Issue by dgaussin** [m0n5t3r/sentry-zabbix#1]
After installation the extension is displayed twice like this :

![image](https://cloud.githubusercontent.com/assets/776304/15432731/c1714144-1eaf-11e6-9f66-409e192888d3.png)

Same thing in the integration list in admin.

**Comment by JustDolanIt** [comment]
May be fixed by commenting out 15th line in **init**.py - seems like Sentry registers modules itself just fine

**Comment by m0n5t3r** [comment]
I somehow missed this when it was opened, sorry...
