### ISSUE TITLE
Error sending data to Zabbix 3.2

### ISSUE THREAD

**Issue by cmmata** [m0n5t3r/sentry-zabbix#2]
Hello,

I have Zabbix server 3.2.1 and Sentry 8.10.0. I have just installed sentry-zabbix executing `pip install sentry-zabbix`, restarted all sentry processes, and configured it in some projects with Zabbix server IP and names.

Now I'm having an error `TypeErrorsentry.tasks.post_process.post_process_group` with message `Error while sending data to Zabbix: an integer is required`.

![screenshot](https://cloud.githubusercontent.com/assets/4223148/21223318/d3a3a0e4-c2c6-11e6-83d2-8672ddf444fa.png)
![screenshot2](https://cloud.githubusercontent.com/assets/4223148/21223317/d3a1b3ba-c2c6-11e6-86a7-f4cdab85dea6.png)

Do you need more info?

**Comment by m0n5t3r** [comment]
please test (I bumped the version and pushed to pypi) and reopen if necessary

**Comment by cmmata** [comment]
I updated it and looks like it's working now. Thank you for your quick response and fix!
